//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("application.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webdeveloptmentkfcteam.
        /// </summary>
        internal static string GeneralKeyToEncrypt {
            get {
                return ResourceManager.GetString("GeneralKeyToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo client de la plantilla no puede estar vacio.
        /// </summary>
        internal static string MessaFieldTemplateClient {
            get {
                return ResourceManager.GetString("MessaFieldTemplateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las entidades no pueden estar vacias.
        /// </summary>
        internal static string MessageFieldEntities {
            get {
                return ResourceManager.GetString("MessageFieldEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo nombre de la entidad no puede estar vacio.
        /// </summary>
        internal static string MessageFieldEntityName {
            get {
                return ResourceManager.GetString("MessageFieldEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo entityTarget no puede estar vacio.
        /// </summary>
        internal static string MessageFieldEntityTarget {
            get {
                return ResourceManager.GetString("MessageFieldEntityTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las entidades del destino no puede estar vacias.
        /// </summary>
        internal static string MessageFieldTargetEntities {
            get {
                return ResourceManager.GetString("MessageFieldTargetEntities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo nombre de las entidades del destino no puede estar vacio.
        /// </summary>
        internal static string MessageFieldTargetEntityName {
            get {
                return ResourceManager.GetString("MessageFieldTargetEntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo origins de la plantilla no puede estar vacio.
        /// </summary>
        internal static string MessageFieldTemplateOrigin {
            get {
                return ResourceManager.GetString("MessageFieldTemplateOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El campo transformationKey no puede estar vacio.
        /// </summary>
        internal static string MessageFieldTransformationKey {
            get {
                return ResourceManager.GetString("MessageFieldTransformationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se encontaron campos vacios en la plantilla.
        /// </summary>
        internal static string MessageTemplateGeneral {
            get {
                return ResourceManager.GetString("MessageTemplateGeneral", resourceCulture);
            }
        }
    }
}
