//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceInfra {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceInfra() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("infrastructure.ResourceInfra", typeof(ResourceInfra).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:5199.
        /// </summary>
        internal static string audience {
            get {
                return ResourceManager.GetString("audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requestdb.
        /// </summary>
        internal static string cosmosDatabase {
            get {
                return ResourceManager.GetString("cosmosDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==.
        /// </summary>
        internal static string cosmosPassword {
            get {
                return ResourceManager.GetString("cosmosPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost:8081.
        /// </summary>
        internal static string cosmosServer {
            get {
                return ResourceManager.GetString("cosmosServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users.
        /// </summary>
        internal static string cosmosUsersContainer {
            get {
                return ResourceManager.GetString("cosmosUsersContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webdeveloptmentkfcteam.
        /// </summary>
        internal static string generalKeyToEncrypt {
            get {
                return ResourceManager.GetString("generalKeyToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:5199.
        /// </summary>
        internal static string issuer {
            get {
                return ResourceManager.GetString("issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nats-web-application-development-environtment-developt-by-software-engineers.
        /// </summary>
        internal static string secretKey {
            get {
                return ResourceManager.GetString("secretKey", resourceCulture);
            }
        }
    }
}
